# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js app to Azure Web App - app-advanced3-6
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: npm install and build
        run: |
          npm install
          npm run build
      
      # Simple preparation focusing on just what's needed
      - name: Prepare standalone Next.js deployment
        run: |
          # Create basic deployment directory
          mkdir -p deployment
          
          # Copy just the necessary files
          cp -r .next/standalone/* deployment/
          mkdir -p deployment/.next/static
          cp -r .next/static deployment/.next/
          
          # Copy critical configuration files
          cp web.config deployment/
          cp server.js deployment/
          
          # Copy public directory if it exists
          if [ -d "public" ]; then
            cp -r public deployment/
          fi
      
      # Package just what we need
      - name: Zip deployment package
        run: |
          cd deployment
          zip -r ../release.zip ./*
          cd ..
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      # Extract directly to site directory
      - name: Unzip artifact for deployment
        run: |
          mkdir -p site
          unzip release.zip -d site
      
      # Deploy to Azure with simpler configuration
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-advanced3-6'
          slot-name: 'Production'
          package: ./site
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F64A9934CBB84623AD05EF75A343FF4D }}
        continue-on-error: true
      
      # Keep retry logic
      - name: Retry deployment if failed
        if: steps.deploy-to-webapp.outcome == 'failure'
        run: |
          echo "First deployment attempt failed, waiting 60 seconds before retrying..."
          sleep 60
      
      - name: 'Retry Deploy to Azure Web App'
        if: steps.deploy-to-webapp.outcome == 'failure'
        id: retry-deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-advanced3-6'
          slot-name: 'Production'
          package: ./site
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F64A9934CBB84623AD05EF75A343FF4D }}
